In [92]:
import numpy as np
import cPickle
import os
import gzip

# First exercise: Classifying MNIST with MLPs
In this exercise you will implement a Neural Network (or MLP) and classify the MNIST digits with it.
MNIST is a "well hung" dataset that has been used a lot over the years to benchmark different classification algorithms. 
To learn more about it have a look here: http://yann.lecun.com/exdb/mnist/ .

# Data Loading
We first define a function for downloading and loading MNIST.
**WARNING**: Executing it will obviously use up some space on your machine ;). 

In [93]:
def mnist(datasets_dir='./data'):
    if not os.path.exists(datasets_dir):
        os.mkdir(datasets_dir)
    data_file = os.path.join(datasets_dir, 'mnist.pkl.gz')
    if not os.path.exists(data_file):
        print('... downloading MNIST from the web')
        try:
            import urllib
            urllib.urlretrieve('http://google.com')
        except AttributeError:
            import urllib.request as urllib
        url = 'http://www.iro.umontreal.ca/~lisa/deep/data/mnist/mnist.pkl.gz'
        urllib.urlretrieve(url, data_file)

    print('... loading data')
    # Load the dataset
    f = gzip.open(data_file, 'rb')
    try:
        train_set, valid_set, test_set = cPickle.load(f, encoding="latin1")
    except TypeError:
        train_set, valid_set, test_set = cPickle.load(f)
    f.close()

    test_x, test_y = test_set
    test_x = test_x.astype('float32')
    test_x = test_x.astype('float32').reshape(test_x.shape[0], 1, 28, 28)
    test_y = test_y.astype('int32')
    valid_x, valid_y = valid_set
    valid_x = valid_x.astype('float32')
    valid_x = valid_x.astype('float32').reshape(valid_x.shape[0], 1, 28, 28)
    valid_y = valid_y.astype('int32')
    train_x, train_y = train_set
    train_x = train_x.astype('float32').reshape(train_x.shape[0], 1, 28, 28)
    train_y = train_y.astype('int32')
    rval = [(train_x, train_y), (valid_x, valid_y), (test_x, test_y)]
    print('... done loading data')
    return rval

# Neural Network Layers
We now define "bare bone" neural network layers.
The parts marked with **TODO** are where you should finish the implementation!
Conceptually we will implement the layers as follows:

Each layer has a constructor that takes an input layer plus some additional arguments such as layer size and the activation function name. The layer then uses the provided input layer to compute the layer dimensions, weight shapes, etc. and setup all auxilliary variables.

Each layer then has to provide three functions (as defined in the Layer class below): *output_shape()*, *fprop()* and *brop()*. The output_shape function is used to figure out the shape for the next layer and the *fprop()/bprop()* functions are used to compute forward and backward passes through the network.

In [94]:
# start by defining simple helpers
def sigmoid(x):
    return 1.0/(1.0+np.exp(-x))

def sigmoid_d(x):
    print "[DEBUG] Input to Sigmoid_d:\n{0}\n".format(x)
    ex = np.exp(-x)
    result = ex/np.square(np.ones_like(x) + ex)
    print "[DEBUG] Output of Sigmoid_d:\n{0}\n".format(result)
    return result

def tanh(x):
    return np.tanh(x)

def tanh_d(x):
    print "[DEBUG] Input to tanh_d:\n{0}\n".format(x)
    result = np.ones_like(x) - np.square(np.tanh(x))
    print "[DEBUG] Output of tanh_d:\n{0}\n".format(result)
    return result

def relu(x):
    return np.maximum(0.0, x)

def relu_d(x):
    print "[DEBUG] Input to Relu_d:\n{0}\n".format(x)
    result = np.where(x > 0, 1, 0)
    print "[DEBUG] Output of Relu_d:\n{0}\n".format(result)
    return result

def softmax(x, axis=1):
    # to make the softmax a "safe" operation we will 
    # first subtract the maximum along the specified axis
    # so that np.exp(x) does not blow up!
    # Note that this does not change the output.
    x_max = np.max(x, axis=axis, keepdims=True)
    x_safe = x - x_max
    e_x = np.exp(x_safe)
    return e_x / np.sum(e_x, axis=axis, keepdims=True)

def one_hot(labels):
    """this creates a one hot encoding from a flat vector:
    i.e. given y = [0,2,1]
     it creates y_one_hot = [[1,0,0], [0,0,1], [0,1,0]]
    """
    classes = np.unique(labels)
    n_classes = classes.size
    one_hot_labels = np.zeros(labels.shape + (n_classes,))
    for c in classes:
        one_hot_labels[labels == c, c] = 1
    return one_hot_labels

def unhot(one_hot_labels):
    """ Invert a one hot encoding, creating a flat vector """
    return np.argmax(one_hot_labels, axis=-1)

# then define an activation function class
class Activation(object):
    
    def __init__(self, tname):
        if tname == 'sigmoid':
            self.act = sigmoid
            self.act_d = sigmoid_d
        elif tname == 'tanh':
            self.act = tanh
            self.act_d = tanh_d
        elif tname == 'relu':
            self.act = relu
            self.act_d = relu_d
        else:
            raise ValueError('Invalid activation function.')
            
    def fprop(self, input_values):
        # we need to remember the last input
        # so that we can calculate the derivative with respect
        # to it later on
        self.last_input = input_values
        return self.act(input_values)
    
    def bprop(self, output_grad):
        return output_grad * self.act_d(self.last_input)

# define a base class for layers
class Layer(object):
    
    def fprop(self, input_values):
        """ Calculate layer output for given input 
            (forward propagation). 
        """
        raise NotImplementedError('This is an interface class, please use a derived instance')

    def bprop(self, output_grad):
        """ Calculate input gradient and gradient 
            with respect to weights and bias (backpropagation). 
        """
        raise NotImplementedError('This is an interface class, please use a derived instance')

    def output_size(self):
        """ Calculate size of this layer's output.
        input_shape[0] is the number of samples in the input.
        input_shape[1:] is the shape of the feature.
        """
        raise NotImplementedError('This is an interface class, please use a derived instance')

# define a base class for loss outputs
# an output layer can then simply be derived
# from both Layer and Loss 
class Loss(object):

    def loss(self, output, output_net):
        """ Calculate mean loss given real output and network output. """
        raise NotImplementedError('This is an interface class, please use a derived instance')

    def input_grad(self, output, output_net):
        """ Calculate input gradient given real output and network output. """
        raise NotImplementedError('This is an interface class, please use a derived instance')

# define a base class for parameterized things        
class Parameterized(object):
    
    def params(self):
        """ Return parameters (by reference) """
        raise NotImplementedError('This is an interface class, please use a derived instance')
    
    def grad_params(self):
        """ Return accumulated gradient with respect to params. """
        raise NotImplementedError('This is an interface class, please use a derived instance')

# define a container for providing input to the network
class InputLayer(Layer):
    
    def __init__(self, input_shape):
        if not isinstance(input_shape, tuple):
            raise ValueError("InputLayer requires input_shape as a tuple")
        self.input_shape = input_shape

    def output_size(self):
        return self.input_shape
    
    def fprop(self, input_values):
        return input_values
    
    def bprop(self, output_grad):
        return output_grad
        
class FullyConnectedLayer(Layer, Parameterized):
    """ A standard fully connected hidden layer, as discussed in the lecture.
    """
    
    def __init__(self, input_layer, num_units, 
                 init_stddev, activation_fun=Activation('relu')):
        self.num_units = num_units
        self.activation_fun = activation_fun
        # the input shape will be of size (batch_size, num_units_prev) 
        # where num_units_prev is the number of units in the input 
        # (previous) layer
        self.input_shape = input_layer.output_size()
        # TODO ################################
        # TODO: implement weight initialization
        # TODO ################################
        # this is the weight matrix it should have shape: (num_units_prev, num_units)
        self.W = np.random.standard_normal((self.input_shape[1], self.num_units)) * init_stddev
        # and this is the bias vector of shape: (num_units)
        self.b = np.random.randn(num_units) * init_stddev
        # create dummy variables for parameter gradients
        # no need to change these here!
        self.dW = None
        self.db = None
        print "Initialized instance of FullyConnectedLayer with {0} output units, \
        accepting input of shape {1}, and generated weight matrix of shape {2}".format(
            self.num_units, self.input_shape, self.W.shape)
    
    def output_size(self):
        return (self.input_shape[0], self.num_units)
    
    def fprop(self, input_values):
        # TODO ################################################
        # TODO: implement forward propagation
        # NOTE: you should also handle the case were 
        #       activation_fun is None (meaning no activation)
        #       then this is simply a linear layer
        # TODO ################################################
        # you again want to cache the last_input for the bprop
        # implementation below!
        self.last_input = input_values
        if self.activation_fun is None:
            return input_values
        activations = input_values.dot(self.W) + self.b
        output = self.activation_fun.fprop(activations)
        return output
        
    def bprop(self, output_grad):
        """ Calculate input gradient (backpropagation). """
        # TODO ################################
        # TODO: implement backward propagation
        # TODO ###############################
        
        # HINT: you may have to divide the weights by n
        #       to make gradient checking work 
        #       (since you want to divide the loss by number of inputs)
        n = output_grad.shape[0]
        # accumulate gradient wrt. the parameters first
        # we will need to store these to later update
        # the network after a few forward backward passes
        # the gradient wrt. W should be stored as self.dW
        # the gradient wrt. b should be stored as self.db
        activ_grad = self.activation_fun.bprop(output_grad)
        self.dW = activ_grad.transpose().dot(self.last_input) / n
        self.db = activ_grad.sum(0) / n
        
        # the gradient wrt. the input should be calculated here
        grad_input = activ_grad.dot(self.W.transpose()) / self.num_units
        return grad_input
        
    def params(self):
        return self.W, self.b

    def grad_params(self):
        return self.dW, self.db

# finally we specify the interface for output layers 
# which are layers that also have a loss function
# we will implement two output layers:
#  a Linear, and Softmax (Logistic Regression) layer
# The difference between output layers and and normal 
# layers is that they will be called to compute the gradient
# of the loss through input_grad(). bprop will never 
# be called on them!
class LinearOutput(Layer, Loss):
    """ A simple linear output layer that  
        uses a squared loss (e.g. should be used for regression)
    """
    def __init__(self, input_layer):
        self.input_size = input_layer.output_size()
        
    def output_size(self):
        return (1,)
        
    def fprop(self, input_values):
        return input_values

    def bprop(self, output_grad):
        raise NotImplementedError(
            'LinearOutput should only be used as the last layer of a Network'
            + ' bprop() should thus never be called on it!'
        )
    
    def input_grad(self, Y, Y_pred):
        # TODO ####################################
        # TODO: implement gradient of squared loss
        # TODO ####################################
        inp_grad = Y - Y_pred
        return inp_grad

    def loss(self, Y, Y_pred):
        loss = 0.5 * np.square(Y - Y_pred)
        return np.mean(np.sum(loss, axis=1))

class SoftmaxOutput(Layer, Loss):
    """ A softmax output layer that calculates 
        the negative log likelihood as loss
        and should be used for classification.
    """
    
    def __init__(self, input_layer):
        self.input_size = input_layer.output_size()
        
    def output_size(self):
        return (1,)
    
    def fprop(self, input_values):
        return softmax(input_values)
    
    def bprop(self, output_grad):
        raise NotImplementedError(
            'SoftmaxOutput should only be used as the last layer of a Network'
            + ' bprop() should thus never be called on it!'
        )
    
    def input_grad(self, Y, Y_pred):
        # TODO #######################################################
        # TODO: implement gradient of the negative log likelihood loss
        # TODO #######################################################
        # HINT: since this would involve taking the log 
        #       of the softmax (which is np.exp(x)/np.sum(x, axis=1))
        #       this gradient computation can be simplified a lot! 
        #loss = self.loss(Y, Y_pred)
        inp_grad = Y - softmax(Y_pred)
        return inp_grad

    def loss(self, Y, Y_pred):
        # Assume one-hot encoding of Y
        # calculate softmax first
        out = softmax(Y_pred)
        # to make the loss numerically stable 
        # you may want to add an epsilon in the log ;)
        eps = 1e-10
        # TODO ####################################
        # calculate negative log likelihood
        # TODO ####################################
        loss = - np.log(out + eps) * Y
        return np.sum(loss) / Y.shape[0]
        

# Neural Network class
With all layers in place (and properly implemented by you) we can finally define a neural network.
For our purposes a neural network is simply a collection of layers which we will cycle through and on which we will call fprop and bprop to compute partial derivatives with respect to the input and the parameters.

Pay special attention to the *check_gradients()* function in which you should implement automatic differentiation. This function will become your best friend when checking the correctness of your implementation.

In [99]:
#Global parameter for batch size of gradient descent
GD_BATCH_SIZE = 10

class NeuralNetwork:
    """ Our Neural Network container class.
    """
    def __init__(self, layers):
        self.layers = layers
        
    def _loss(self, X, Y):
        Y_pred = self.predict(X)
        return self.layers[-1].loss(Y, Y_pred)

    def predict(self, X):
        """ Calculate an output Y for the given input X. """
        # TODO ##########################################
        # TODO: implement forward pass through all layers
        # TODO ##########################################
        Y_pred = X
        for layer in self.layers:
            Y_pred = layer.fprop(Y_pred)
        #Y_pred = np.argmax(data, axis=-1)
        return Y_pred
    
    def backpropagate(self, Y, Y_pred, upto=0):
        """ Backpropagation of partial derivatives through 
            the complete network up to layer 'upto'
        """
        print "[DEBUG] Backpropogating upto layer {0}".format(upto)
        if upto >= len(self.layers):
            return
        next_grad = self.layers[-1].input_grad(Y, Y_pred)
        print "[DEBUG] Backpropogated through Output Layer"
        # TODO ###########################################
        # TODO: implement backward pass through all layers
        # TODO ###########################################
        for layer in self.layers[-2:upto:-1]:
            next_grad = layer.bprop(next_grad)
            print "[DEBUG] Backpropogated through one more layer"
        if upto <= len(self.layers) - 2:
            next_grad = self.layers[upto].bprop(next_grad)
            print "[DEBUG] Backpropogated through final requested layer"
        return
    
    def classification_error(self, X, Y):
        """ Calculate error on the given data 
            assuming they are classes that should be predicted. 
        """
        Y_pred = unhot(self.predict(X))
        error = Y_pred != Y
        return np.mean(error)
    
    def sgd_epoch(self, X, Y, learning_rate, batch_size):
        n_samples = X.shape[0]
        n_batches = n_samples // batch_size
        for b in range(n_batches):
            # TODO #####################################
            # Implement stochastic gradient descent here
            # TODO #####################################
            # start by extracting a batch from X and Y
            # (you can assume the inputs are already shuffled)
            start_ind = b * batch_size
            end_ind = min(start_ind + batch_size, n_samples)
            X_batch = X[start_ind:end_ind]
            Y_batch = Y[start_ind:end_ind]
            
            # TODO: then forward and backward propagation + updates
            # HINT: layer.params() returns parameters *by reference*
            #       so you can easily update in-place
            Y_pred = self.predict(X_batch)
            self.backpropogate(Y_batch, Y_pred)
            for layer in self.layers:
                w, bi = layer.params()
                dw, dbi = layer.grad_params()
                w = w - learning_rate * dw
                bi = bi - learning_rate * dbi
        return
    
    def gd_epoch(self, X, Y, learning_rate):
        # TODO ##################################################
        # Implement batch gradient descent here
        # A few hints:
        #   There are two strategies you can follow:
        #   Either shove the whole dataset throught the network
        #   at once (which can be problematic for large datasets)
        #   or run through it batch wise as in the sgd approach
        #   and accumulate the gradients for all parameters as
        #   you go through the data. Either way you should then
        #   do one gradient step after you went through the
        #   complete dataset!
        # TODO ##################################################
        n_samples = X.shape[0]
        n_batches = GD_BATCH_SIZE
        w_upd = []
        bi_upd = []
        #Initialize accumulators for parameter updates with 0s
        for layer in self.layers:
            w, bi = layer.params()
            w_upd.append(np.zeros_like(w))
            bi_upd.append(np.zeros_like(bi))
            
        for b in range(n_batches):
            start_ind = b * batch_size
            end_ind = min(start_ind + batch_size, n_samples)
            X_batch = X[start_ind:end_ind]
            Y_batch = Y[start_ind:end_ind]
            
            Y_pred = self.predict(X_batch)
            self.backpropogate(Y_batch, Y_pred)
            for i, layer in enumerate(self.layers):
                dw, dbi = layer.grad_params()
                w_upd[i] += dw
                bi_upd[i] += dbi
            
        for i, layer in enumerate(self.layers):
            w, bi = layer.params()
            w = w - learning_rate * w_upd[i]
            bi = bi - learning_rate * bi_upd[i]
        return
    
    def train(self, X, Y, X_valid, Y_valid, learning_rate=0.1, max_epochs=100, 
              batch_size=64, descent_type="sgd", y_one_hot=True):
        """ Train network on the given data. """
        n_samples = X.shape[0]
        n_batches = n_samples // batch_size
        if y_one_hot:
            Y_train = one_hot(Y)
        else:
            Y_train = Y
        print("... starting training")
        for e in range(max_epochs+1):
            if descent_type == "sgd":
                self.sgd_epoch(X, Y_train, learning_rate, batch_size)
            elif descent_type == "gd":
                self.gd_epoch(X, Y_train, learning_rate)
            else:
                raise NotImplementedError("Unknown gradient descent type {}".format(descent_type))

            # Output error on the training data
            train_loss = self._loss(X, Y_train)
            train_error = self.classification_error(X, Y)
            print('epoch {:.4f}, loss {:.4f}, train error {:.4f}'.format(e, train_loss, train_error))
            # TODO ##################################################
            # compute error on validation data:
            # simply make the function take validation data as input
            # and then compute errors here and print them
            # TODO ##################################################
            
            # Output error on the validation data
            valid_loss = self._loss(X_valid, Y_valid)
            valid_error = self.classification_error(X_valid, Y_valid)
            print('epoch {:.4f}, loss {:.4f}, valid error {:.4f}'.format(e, train_loss, train_error))
    
    def check_gradients(self, X, Y):
        """ Helper function to test the parameter gradients for
        correctness. """
        num_layers = len(self.layers)
        for ind, layer in enumerate(self.layers[::-1]):
            l = num_layers - ind - 1
            if isinstance(layer, Parameterized):
                print('checking gradient for layer {}'.format(l))
                for p, param in enumerate(layer.params()):
                    # we iterate through all parameters
                    param_shape = param.shape
                    print "checking parameter {0} with shape {1}".format(p, param_shape)
                    # define functions for conveniently swapping
                    # out parameters of this specific layer and 
                    # computing loss and gradient with these 
                    # changed parametrs
                    def output_given_params(param_new):
                        """ A function that will compute the output 
                            of the network given a set of parameters
                        """
                        # copy provided parameters
                        param[:] = np.reshape(param_new, param_shape)
                        # return computed loss
                        return self._loss(X, Y)

                    def grad_given_params(param_new):
                        """A function that will compute the gradient 
                           of the network given a set of parameters
                        """
                        # copy provided parameters
                        param[:] = np.reshape(param_new, param_shape)
                        # Forward propagation through the net
                        Y_pred = self.predict(X)
                        # Backpropagation of partial derivatives
                        self.backpropagate(Y, Y_pred, upto=l)
                        # return the computed gradient 
                        return np.ravel(self.layers[l].grad_params()[p])

                    # let the initial parameters be the ones that
                    # are currently placed in the network and flatten them
                    # to a vector for convenient comparisons, printing etc.
                    param_init = np.ravel(np.copy(param))
                    
                    # TODO ####################################
                    # TODO compute the gradient with respect to
                    #      the initial parameters in two ways:
                    #      1) with grad_given_params()
                    #      2) with finite differences 
                    #         using output_given_params()
                    #         (as discussed in the lecture)
                    #      if your implementation is correct 
                    #      both results should be epsilon close
                    #      to each other!
                    # TODO ####################################
                    epsilon = 1e-4
                    # making sure your gradient checking routine itself 
                    # has no errors can be a bit tricky. To debug it
                    # you can "cheat" by using scipy which implements
                    # gradient checking exactly the way you should!
                    # To do that simply run the following here:
#                     import scipy.optimize
#                     err = scipy.optimize.check_grad(output_given_params, 
#                                                     grad_given_params, param_init)
                    
#                     print('diff {:.2e}'.format(err))
#                     try:
#                         assert(err < epsilon)
#                     except AssertionError:
#                         print "Encountered improperly implemented gradient calculation \
#                         in parameter number {0} of layer {1}".format(p, l)
                    loss_base = output_given_params(param_init)
                    TODO this should hold the gradient as calculated through bprop
                    gparam_bprop = grad_given_params(param_init) 
                    TODO this should hold the gradient calculated through 
                         finite differences
                    for i in range(len(param_init)):
                        print "[DEBUG] Checking parameter number {0}".format(i)
                        param_hat = np.copy(param_init)
                        param_hat[i] += epsilon                            
                        loss_hat = output_given_params(param_hat)
                        gparam_fd = (loss_hat - loss_base) / epsilon
                    # calculate difference between them
                        err = np.mean(np.abs(gparam_bprop - gparam_fd))
                        print('diff {:.2e}'.format(err))
                        try:
                            assert(err < epsilon)
                        except AssertionError:
                            print "Encountered improperly implemented gradient calculation"
                            return
                    
                    # reset the parameters to their initial values
                    param[:] = np.reshape(param_init, param_shape)

# Gradient Checking
After implementing everything it is always a good idea to setup some layers and perform gradient
checking on random data. **Note** that this is only an example! It is not a useful network architecture ;). We also expect you to play around with this to test all your implemented components.

In [100]:
input_shape = (5, 10)
n_labels = 6
layers = [InputLayer(input_shape)]

layers.append(FullyConnectedLayer(
                layers[-1],
                num_units=15,
                init_stddev=0.1,
                activation_fun=Activation('relu')
))
layers.append(FullyConnectedLayer(
                layers[-1],
                num_units=6,
                init_stddev=0.1,
                activation_fun=Activation('tanh')
))
layers.append(FullyConnectedLayer(
                layers[-1],
                num_units=n_labels,
                init_stddev=0.1,
                activation_fun=Activation('relu')
))
layers.append(SoftmaxOutput(layers[-1]))
nn = NeuralNetwork(layers)

Initialized instance of FullyConnectedLayer with 15 output units,         accepting input of shape (5, 10), and generated weight matrix of shape (10, 15)
Initialized instance of FullyConnectedLayer with 6 output units,         accepting input of shape (5, 15), and generated weight matrix of shape (15, 6)
Initialized instance of FullyConnectedLayer with 6 output units,         accepting input of shape (5, 6), and generated weight matrix of shape (6, 6)


In [101]:
# create random data
X = np.random.normal(size=input_shape)
# and random labels
Y = np.zeros((input_shape[0], n_labels))
for i in range(Y.shape[0]):
    idx = np.random.randint(n_labels)
    Y[i, idx] = 1.

In [102]:

sig_act = Activation('sigmoid')
tanh_act = Activation('tanh')
relu_act = Activation('relu')
acts = [sig_act, tanh_act, relu_act]
data = np.random.standard_normal((5, 10))
for act in acts:
    output_original = act.fprop(data)
    for data_hat = 
    grad = act.bprop()
#nn.check_gradients(X, Y)

checking gradient for layer 3
checking parameter 0 with shape (6, 6)
[DEBUG] Backpropogating upto layer 3
[DEBUG] Backpropogated through Output Layer
[DEBUG] Input to Relu_d:
[[-0.06604504  0.06578212 -0.01829063  0.15557494  0.18223684 -0.27596964]
 [-0.05739457  0.0243757  -0.06532936  0.14069002  0.1981096  -0.28868001]
 [-0.06897451  0.01718996 -0.07211527  0.14788229  0.20713804 -0.26243068]
 [-0.07095856  0.02674788 -0.05350347  0.13832206  0.18847151 -0.27716806]
 [-0.06206882  0.03164214 -0.06116579  0.15258074  0.20782719 -0.27455227]]

[DEBUG] Output of Relu_d:
[[0 1 0 1 1 0]
 [0 1 0 1 1 0]
 [0 1 0 1 1 0]
 [0 1 0 1 1 0]
 [0 1 0 1 1 0]]

[DEBUG] Backpropogated through final requested layer
diff 4.74e-02
Encountered improperly implemented gradient calculation                         in parameter number 0 of layer 3
checking parameter 1 with shape (6,)
[DEBUG] Backpropogating upto layer 3
[DEBUG] Backpropogated through Output Layer
[DEBUG] Input to Relu_d:
[[-0.06604504  0.06578

# Training on MNIST
Finally we can let our network run on the MNIST dataset!

First load the data and reshape it.

In [77]:
# load
Dtrain, Dval, Dtest = mnist()
X_train, y_train = Dtrain
# Downsample training data to make it a bit faster for testing this code
n_train_samples = 10000
train_idxs = np.random.permutation(X_train.shape[0])[:n_train_samples]
X_train = X_train[train_idxs]
y_train = y_train[train_idxs]

... downloading MNIST from the web
... loading data


MemoryError: 

*Dtrain* contains 50k images which are of size 28 x 28 pixels. Hence:

In [ ]:
print("X_train shape: {}".format(np.shape(X_train)))
print("y_train shape: {}".format(np.shape(y_train)))

y_train will automatically be converted in the *train()* function to one_hot encoding.


But we need to reshape X_train, as our Network expects flat vectors of size 28*28 as input!

In [ ]:
X_train = X_train.reshape(X_train.shape[0], -1)
print("Reshaped X_train size: {}".format(X_train.shape))

Ah, much better ;-)! 

Now we can finally really start training a Network!


I pre-defined a small Network for you below. Again This is not really a good default and will not produce state of the art results. Please play around with this a bit. See how different activation functions and training procedures (gd / sgd) affect the result.

In [ ]:
import time

# Setup a small MLP / Neural Network
# we can set the first shape to None here to indicate that
# we will input a variable number inputs to the network
input_shape = (None, 28*28)
layers = [InputLayer(input_shape)]
layers.append(FullyConnectedLayer(
                layers[-1],
                num_units=100,
                init_stddev=0.01,
                activation_fun=Activation('relu')
))
layers.append(FullyConnectedLayer(
                layers[-1],
                num_units=100,
                init_stddev=0.01,
                activation_fun=Activation('relu')
))
layers.append(FullyConnectedLayer(
                layers[-1],
                num_units=10,
                init_stddev=0.01,
                # last layer has no nonlinearity 
                # (softmax will be applied in the output layer)
                activation_fun=None 
))
layers.append(SoftmaxOutput(layers[-1]))

nn = NeuralNetwork(layers)
# Train neural network
t0 = time.time()
nn.train(X_train, y_train, learning_rate=0.1, 
         max_epochs=20, batch_size=64, y_one_hot=True)
t1 = time.time()
print('Duration: {:.1f}s'.format(t1-t0))

# Figure out a reasonable Network that achieves good performance
As the last part of this task, setup a network that works well and gets reasonable accuracy, say ~ 1-3 percent error on the **validation set**. 
Train this network on the complete data and compute the **test error**. 

Once you have done this, visualize a few digits from the the test set that the network gets right as well as a few that the network gets wrong!